<?php

namespace Ss\MembreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmiRepository extends EntityRepository
{
}
