ss_fichier_dossier:
    pattern:  /dossier-{id}-{emplacement}
    defaults: { _controller: SsFichierBundle:Fichier:dossier }
    requirements:
        id:  \d+

ss_fichier_uploader:
    pattern:  /uploader-{id}-{emplacement}
    defaults: { _controller: SsFichierBundle:Fichier:uploader }
    requirements:
        id:  \d+

ss_fichier_telecharger:
    pattern:  /telecharger-{ext}-{fichier}
    defaults: { _controller: SsFichierBundle:Fichier:telecharger }

ss_fichier_index:
    pattern:  /
    defaults: { _controller: SsFichierBundle:Fichier:index }
