<?php

namespace Ss\FichierBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FichierController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ss\FichierBundle\Controller\FichierController();
        return $instance;
    }
}
