<?php

namespace EnhancedProxy06b87f87_154c6a1daef2eaa09ebbc3e95753ac49b6e3370e\__CG__\Ss\MembreBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MembreController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/SS/app/cache/dev/jms_diextra/proxies/EnhancedProxy06b87f87_154c6a1daef2eaa09ebbc3e95753ac49b6e3370e-__CG__-Ss-MembreBundle-Controller-MembreController.php';
        $d = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ss\\MembreBundle\\Controller\\MembreController' => array('profilAction' => array(0 => 'security.access.method_interceptor'), 'demanderAmiAction' => array(0 => 'security.access.method_interceptor'), 'bannirAction' => array(0 => 'security.access.method_interceptor'), 'accepterAmiAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy06b87f87_ca6cb599cab3efa00ce35e03c1dcb407344ff24c\__CG__\Ss\MembreBundle\Controller\MembreController();
        $instance->__CGInterception__setLoader($d);
        return $instance;
    }
}
