<?php

namespace Ss\FichierBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FichierController__JMSInjector
{
    public static function inject($container) {
        require_once '/var/www/SS/app/cache/dev/jms_diextra/proxies/Ss-FichierBundle-Controller-FichierController.php';
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Ss\\FichierBundle\\Controller\\FichierController' => array('dossierAction' => array(0 => 'security.access.method_interceptor'), 'telechargerAction' => array(0 => 'security.access.method_interceptor'))));
        $instance = new \EnhancedProxy7e71fbef_8324223486c3fd91459bd17b5ca3e126c26f9a1b\__CG__\Ss\FichierBundle\Controller\FichierController();
        $instance->__CGInterception__setLoader($a);
        return $instance;
    }
}
