parameters:
#    ss_membre.example.class: Ss\MembreBundle\Example

services:
#    ss_membre.example:
#        class: %ss_membre.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ss_membre.registration.form.type:
        class: Ss\MembreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ss_membre_inscription }
            
    ss_membre.profile.form.type:
        class: Ss\MembreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ss_membre_profil }
